export const THEMES = [
  { id: "campus", label: "Campus", blurb: "Navy headings on pale paper", scheme: "light", swatch: "#12385A" },
  { id: "light", label: "Light", blurb: "Black type on white", scheme: "light", swatch: "#111827" },
  { id: "pearl", label: "Pearl", blurb: "Warm ink on cream", scheme: "light", swatch: "#3D5368" },
  { id: "dawn", label: "Dawn", blurb: "Sunrise coral headings", scheme: "light", swatch: "#B4482D" },
  { id: "sky", label: "Sky", blurb: "Bright blue on ice", scheme: "light", swatch: "#0F6FBF" },
  { id: "blush", label: "Blush", blurb: "Rose type on petal", scheme: "light", swatch: "#9B3D5A" },
  { id: "sand", label: "Sand", blurb: "Clay type on beige", scheme: "light", swatch: "#7A4E2D" },
  { id: "pine", label: "Pine", blurb: "Forest type on sage", scheme: "light", swatch: "#1F5A44" },
  { id: "slate", label: "Slate", blurb: "Stone type on grey", scheme: "light", swatch: "#3A4552" },
  { id: "midnight", label: "Midnight", blurb: "Pale type on ink", scheme: "dark", swatch: "#7EB0D8" },
  { id: "dark", label: "Dark", blurb: "White type on black", scheme: "dark", swatch: "#F4F4F5" },
  { id: "ember", label: "Ember", blurb: "Warm type on charcoal", scheme: "dark", swatch: "#F0B27A" },
  { id: "ocean", label: "Ocean", blurb: "Aqua type on deep blue", scheme: "dark", swatch: "#7FDBDA" },
  { id: "forest", label: "Forest", blurb: "Mint type on pine black", scheme: "dark", swatch: "#8FCB9B" },
  { id: "aurora", label: "Aurora", blurb: "Lilac type on indigo", scheme: "dark", swatch: "#C4B5FD" },
] as const;

export const BACKGROUNDS = [
  { id: "linen", label: "Linen", blurb: "Vertical paper grain", kind: "pattern" },
  { id: "grid", label: "Grid", blurb: "Notebook squares", kind: "pattern" },
  { id: "dots", label: "Dotted", blurb: "Dot-grid sheet", kind: "pattern" },
  { id: "waves", label: "Waves", blurb: "Soft ripples", kind: "pattern" },
  { id: "diagonal", label: "Diagonal", blurb: "Angled hatch", kind: "pattern" },
  { id: "stripes", label: "Stripes", blurb: "Notebook rules", kind: "pattern" },
  { id: "chevron", label: "Chevron", blurb: "Folded paper", kind: "pattern" },
  { id: "mesh", label: "Mesh", blurb: "Crossed lines", kind: "pattern" },
  { id: "stars", label: "Stars", blurb: "Sparse sparkle", kind: "pattern" },
  { id: "paper", label: "Fibre", blurb: "Paper fibres", kind: "pattern" },
  { id: "wash", label: "Wash", blurb: "Light in the corner", kind: "pattern" },
  { id: "bloom", label: "Bloom", blurb: "Two colour glows", kind: "pattern" },
  { id: "solid", label: "Solid", blurb: "Plain colour", kind: "colour" },
  { id: "campus", label: "Courtyard", blurb: "Campus photograph", kind: "photo" },
  { id: "library", label: "Library", blurb: "Reading hall photo", kind: "photo" },
  { id: "laboratory", label: "Laboratories", blurb: "Lab photograph", kind: "photo" },
  { id: "lecture", label: "Lecture hall", blurb: "Theatre photograph", kind: "photo" },
  { id: "exterior", label: "Exterior", blurb: "College front", kind: "photo" },
] as const;

export type ThemeId = (typeof THEMES)[number]["id"];
export type BackgroundId = (typeof BACKGROUNDS)[number]["id"];

export const THEME_KEY = "lms.theme";
export const BACKGROUND_KEY = "lms.background";

export const PHOTO_BACKGROUNDS: Partial<Record<BackgroundId, string>> = {
  campus: "/campus/courtyard.jpg",
  library: "/campus/library.jpg",
  laboratory: "/campus/laboratory.jpg",
  lecture: "/campus/lecture.jpg",
  exterior: "/campus/exterior.jpg",
};

type Tokens = Record<string, string>;

export const THEME_TOKENS: Record<ThemeId, Tokens> = {
  campus: {
    "--lms-ink": "#122033",
    "--lms-ink-soft": "#2a3b4e",
    "--lms-muted": "#5c6b7a",
    "--lms-faint": "#8a97a6",
    "--lms-paper": "#f3f5f8",
    "--lms-paper-2": "#e8edf3",
    "--lms-surface": "#ffffff",
    "--lms-navy": "#12385a",
    "--lms-navy-2": "#0d2c48",
    "--lms-navy-3": "#1a4a73",
    "--lms-primary": "#1b4f8a",
    "--lms-primary-fg": "#ffffff",
    "--lms-accent": "#2a6bb0",
    "--lms-line": "#d7dee7",
    "--lms-line-strong": "#b7c3d1",
    "--lms-ok": "#1f7a5c",
    "--lms-ok-bg": "#e7f5ef",
    "--lms-warn": "#9a6b14",
    "--lms-warn-bg": "#f8efd8",
    "--lms-danger": "#a33b3b",
    "--lms-danger-bg": "#f8e8e8",
    "--lms-info-bg": "#e7eef7",
    "--lms-heading": "#12385a",
  },
  light: {
    "--lms-ink": "#111827",
    "--lms-ink-soft": "#1f2937",
    "--lms-muted": "#4b5563",
    "--lms-faint": "#9ca3af",
    "--lms-paper": "#fafafa",
    "--lms-paper-2": "#f3f4f6",
    "--lms-surface": "#ffffff",
    "--lms-navy": "#111827",
    "--lms-navy-2": "#030712",
    "--lms-navy-3": "#374151",
    "--lms-primary": "#2563eb",
    "--lms-primary-fg": "#ffffff",
    "--lms-accent": "#3b82f6",
    "--lms-line": "#e5e7eb",
    "--lms-line-strong": "#d1d5db",
    "--lms-ok": "#15803d",
    "--lms-ok-bg": "#ecfdf3",
    "--lms-warn": "#b45309",
    "--lms-warn-bg": "#fff7ed",
    "--lms-danger": "#b91c1c",
    "--lms-danger-bg": "#fef2f2",
    "--lms-info-bg": "#eff6ff",
    "--lms-heading": "#020617",
  },
  pearl: {
    "--lms-ink": "#1c1914",
    "--lms-ink-soft": "#3a342c",
    "--lms-muted": "#6b6358",
    "--lms-faint": "#948b7e",
    "--lms-paper": "#f4f0e8",
    "--lms-paper-2": "#e8e1d4",
    "--lms-surface": "#fbf8f2",
    "--lms-navy": "#2c3a4a",
    "--lms-navy-2": "#22303e",
    "--lms-navy-3": "#3d5166",
    "--lms-primary": "#3d5368",
    "--lms-primary-fg": "#fbf8f2",
    "--lms-accent": "#4d6880",
    "--lms-line": "#d9d0c3",
    "--lms-line-strong": "#c4b8a6",
    "--lms-ok": "#2f6b52",
    "--lms-ok-bg": "#e5f0ea",
    "--lms-warn": "#8a6a24",
    "--lms-warn-bg": "#f3ead4",
    "--lms-danger": "#9a3f3f",
    "--lms-danger-bg": "#f3e4e4",
    "--lms-info-bg": "#e7ecef",
    "--lms-heading": "#2c3a4a",
  },
  dawn: {
    "--lms-ink": "#3b1d14",
    "--lms-ink-soft": "#5c2e20",
    "--lms-muted": "#8a5a48",
    "--lms-faint": "#b08978",
    "--lms-paper": "#fff4ec",
    "--lms-paper-2": "#f8e4d6",
    "--lms-surface": "#fffaf6",
    "--lms-navy": "#7a2e1c",
    "--lms-navy-2": "#5c2114",
    "--lms-navy-3": "#9a3d26",
    "--lms-primary": "#c45c32",
    "--lms-primary-fg": "#fffaf6",
    "--lms-accent": "#e07a4a",
    "--lms-line": "#f0d2c2",
    "--lms-line-strong": "#e0b49e",
    "--lms-ok": "#2f6b52",
    "--lms-ok-bg": "#e5f0ea",
    "--lms-warn": "#b45309",
    "--lms-warn-bg": "#fff4e0",
    "--lms-danger": "#b91c1c",
    "--lms-danger-bg": "#fde8e8",
    "--lms-info-bg": "#fbeee6",
    "--lms-heading": "#b4482d",
  },
  sky: {
    "--lms-ink": "#0b2a44",
    "--lms-ink-soft": "#163e5f",
    "--lms-muted": "#4a7394",
    "--lms-faint": "#7fa0b8",
    "--lms-paper": "#eef8ff",
    "--lms-paper-2": "#d7ecfb",
    "--lms-surface": "#f7fbff",
    "--lms-navy": "#0b4f86",
    "--lms-navy-2": "#083a64",
    "--lms-navy-3": "#1567a8",
    "--lms-primary": "#0f6fbf",
    "--lms-primary-fg": "#f7fbff",
    "--lms-accent": "#2b8fe0",
    "--lms-line": "#c5e0f4",
    "--lms-line-strong": "#9cc8e6",
    "--lms-ok": "#0f766e",
    "--lms-ok-bg": "#e6f7f4",
    "--lms-warn": "#b45309",
    "--lms-warn-bg": "#fff4e0",
    "--lms-danger": "#b91c1c",
    "--lms-danger-bg": "#fde8e8",
    "--lms-info-bg": "#e3f2fd",
    "--lms-heading": "#0b4f86",
  },
  blush: {
    "--lms-ink": "#3a1524",
    "--lms-ink-soft": "#5a2438",
    "--lms-muted": "#8a4d63",
    "--lms-faint": "#b07d90",
    "--lms-paper": "#fff1f5",
    "--lms-paper-2": "#f8dce6",
    "--lms-surface": "#fff7fa",
    "--lms-navy": "#6e243c",
    "--lms-navy-2": "#52182c",
    "--lms-navy-3": "#8a3350",
    "--lms-primary": "#9b3d5a",
    "--lms-primary-fg": "#fff7fa",
    "--lms-accent": "#c45d7a",
    "--lms-line": "#f0cdd8",
    "--lms-line-strong": "#e0a8ba",
    "--lms-ok": "#2f6b52",
    "--lms-ok-bg": "#e5f0ea",
    "--lms-warn": "#b45309",
    "--lms-warn-bg": "#fff4e0",
    "--lms-danger": "#9f1239",
    "--lms-danger-bg": "#fde8ef",
    "--lms-info-bg": "#fbeaf0",
    "--lms-heading": "#9b3d5a",
  },
  sand: {
    "--lms-ink": "#3a2718",
    "--lms-ink-soft": "#5a3c24",
    "--lms-muted": "#8a6a4e",
    "--lms-faint": "#b39a7e",
    "--lms-paper": "#f7f0e4",
    "--lms-paper-2": "#eadcc6",
    "--lms-surface": "#fbf7f0",
    "--lms-navy": "#5c3a22",
    "--lms-navy-2": "#432a18",
    "--lms-navy-3": "#7a4e2d",
    "--lms-primary": "#7a4e2d",
    "--lms-primary-fg": "#fbf7f0",
    "--lms-accent": "#a86b3c",
    "--lms-line": "#e2d2ba",
    "--lms-line-strong": "#cbb690",
    "--lms-ok": "#3f6b3a",
    "--lms-ok-bg": "#e8f0e4",
    "--lms-warn": "#b45309",
    "--lms-warn-bg": "#fff4e0",
    "--lms-danger": "#9a3f3f",
    "--lms-danger-bg": "#f3e4e4",
    "--lms-info-bg": "#efe6d8",
    "--lms-heading": "#5c3a22",
  },
  pine: {
    "--lms-ink": "#13241c",
    "--lms-ink-soft": "#234034",
    "--lms-muted": "#4f6a5e",
    "--lms-faint": "#7a9186",
    "--lms-paper": "#eef4f0",
    "--lms-paper-2": "#dce8e1",
    "--lms-surface": "#f7faf8",
    "--lms-navy": "#143028",
    "--lms-navy-2": "#0f241e",
    "--lms-navy-3": "#1d463a",
    "--lms-primary": "#1f5a44",
    "--lms-primary-fg": "#f7faf8",
    "--lms-accent": "#2f6b52",
    "--lms-line": "#c9d7d0",
    "--lms-line-strong": "#a9bfb4",
    "--lms-ok": "#1f7a5c",
    "--lms-ok-bg": "#e3f2eb",
    "--lms-warn": "#8a6a24",
    "--lms-warn-bg": "#f3ead4",
    "--lms-danger": "#9a3f3f",
    "--lms-danger-bg": "#f3e4e4",
    "--lms-info-bg": "#e3eee8",
    "--lms-heading": "#143028",
  },
  slate: {
    "--lms-ink": "#1b1f24",
    "--lms-ink-soft": "#32383f",
    "--lms-muted": "#5c656e",
    "--lms-faint": "#8a929a",
    "--lms-paper": "#eef0f3",
    "--lms-paper-2": "#e1e4e9",
    "--lms-surface": "#f7f8fa",
    "--lms-navy": "#2a3038",
    "--lms-navy-2": "#1f242b",
    "--lms-navy-3": "#3c4450",
    "--lms-primary": "#3a4552",
    "--lms-primary-fg": "#f7f8fa",
    "--lms-accent": "#526070",
    "--lms-line": "#d4d8de",
    "--lms-line-strong": "#b7bdc6",
    "--lms-ok": "#2f6b52",
    "--lms-ok-bg": "#e5f0ea",
    "--lms-warn": "#8a6a24",
    "--lms-warn-bg": "#f3ead4",
    "--lms-danger": "#9a3f3f",
    "--lms-danger-bg": "#f3e4e4",
    "--lms-info-bg": "#e8ebef",
    "--lms-heading": "#2a3038",
  },
  midnight: {
    "--lms-ink": "#e8eef4",
    "--lms-ink-soft": "#c5d0db",
    "--lms-muted": "#8fa0b0",
    "--lms-faint": "#6d7e8e",
    "--lms-paper": "#0e1620",
    "--lms-paper-2": "#162230",
    "--lms-surface": "#152232",
    "--lms-navy": "#0a1420",
    "--lms-navy-2": "#071018",
    "--lms-navy-3": "#1c334c",
    "--lms-primary": "#7eb0d8",
    "--lms-primary-fg": "#0a1420",
    "--lms-accent": "#8fbce0",
    "--lms-line": "#243548",
    "--lms-line-strong": "#35506a",
    "--lms-ok": "#6ec7a5",
    "--lms-ok-bg": "#16362c",
    "--lms-warn": "#e0c27a",
    "--lms-warn-bg": "#3a3018",
    "--lms-danger": "#e08a8a",
    "--lms-danger-bg": "#3a1c1c",
    "--lms-info-bg": "#1a2c40",
    "--lms-heading": "#e8eef4",
  },
  dark: {
    "--lms-ink": "#f4f4f5",
    "--lms-ink-soft": "#d4d4d8",
    "--lms-muted": "#a1a1aa",
    "--lms-faint": "#71717a",
    "--lms-paper": "#09090b",
    "--lms-paper-2": "#18181b",
    "--lms-surface": "#121214",
    "--lms-navy": "#000000",
    "--lms-navy-2": "#000000",
    "--lms-navy-3": "#27272a",
    "--lms-primary": "#e4e4e7",
    "--lms-primary-fg": "#09090b",
    "--lms-accent": "#fafafa",
    "--lms-line": "#27272a",
    "--lms-line-strong": "#3f3f46",
    "--lms-ok": "#4ade80",
    "--lms-ok-bg": "#052e16",
    "--lms-warn": "#fbbf24",
    "--lms-warn-bg": "#422006",
    "--lms-danger": "#fb7185",
    "--lms-danger-bg": "#4c0519",
    "--lms-info-bg": "#18181b",
    "--lms-heading": "#fafafa",
  },
  ember: {
    "--lms-ink": "#f6e7d8",
    "--lms-ink-soft": "#e4c8a8",
    "--lms-muted": "#c4a07c",
    "--lms-faint": "#8e6e52",
    "--lms-paper": "#1a120e",
    "--lms-paper-2": "#2a1c16",
    "--lms-surface": "#241914",
    "--lms-navy": "#120c0a",
    "--lms-navy-2": "#0c0806",
    "--lms-navy-3": "#3a241c",
    "--lms-primary": "#f0b27a",
    "--lms-primary-fg": "#1a120e",
    "--lms-accent": "#f3c79a",
    "--lms-line": "#3d2a20",
    "--lms-line-strong": "#5a3c2c",
    "--lms-ok": "#86efac",
    "--lms-ok-bg": "#14532d",
    "--lms-warn": "#fbbf24",
    "--lms-warn-bg": "#422006",
    "--lms-danger": "#fb7185",
    "--lms-danger-bg": "#4c0519",
    "--lms-info-bg": "#2a1c16",
    "--lms-heading": "#f6e7d8",
  },
  ocean: {
    "--lms-ink": "#d7f6f5",
    "--lms-ink-soft": "#b3e4e6",
    "--lms-muted": "#7aa8b4",
    "--lms-faint": "#4f7c88",
    "--lms-paper": "#07151c",
    "--lms-paper-2": "#0d2430",
    "--lms-surface": "#0b1e28",
    "--lms-navy": "#041016",
    "--lms-navy-2": "#020b10",
    "--lms-navy-3": "#123344",
    "--lms-primary": "#7fdbda",
    "--lms-primary-fg": "#07151c",
    "--lms-accent": "#9ae6e5",
    "--lms-line": "#163846",
    "--lms-line-strong": "#21586a",
    "--lms-ok": "#5eead4",
    "--lms-ok-bg": "#134e4a",
    "--lms-warn": "#fbbf24",
    "--lms-warn-bg": "#422006",
    "--lms-danger": "#fb7185",
    "--lms-danger-bg": "#4c0519",
    "--lms-info-bg": "#0d2430",
    "--lms-heading": "#d7f6f5",
  },
  forest: {
    "--lms-ink": "#dff3e4",
    "--lms-ink-soft": "#b7dcc0",
    "--lms-muted": "#7fa88a",
    "--lms-faint": "#587864",
    "--lms-paper": "#0c1610",
    "--lms-paper-2": "#16241b",
    "--lms-surface": "#121c16",
    "--lms-navy": "#08110c",
    "--lms-navy-2": "#050a07",
    "--lms-navy-3": "#1c3324",
    "--lms-primary": "#8fcb9b",
    "--lms-primary-fg": "#0c1610",
    "--lms-accent": "#a7dbb2",
    "--lms-line": "#1e3326",
    "--lms-line-strong": "#2f4d3a",
    "--lms-ok": "#86efac",
    "--lms-ok-bg": "#14532d",
    "--lms-warn": "#fbbf24",
    "--lms-warn-bg": "#422006",
    "--lms-danger": "#fb7185",
    "--lms-danger-bg": "#4c0519",
    "--lms-info-bg": "#16241b",
    "--lms-heading": "#dff3e4",
  },
  aurora: {
    "--lms-ink": "#ede9fe",
    "--lms-ink-soft": "#ddd6fe",
    "--lms-muted": "#a78bfa",
    "--lms-faint": "#7c6aa8",
    "--lms-paper": "#12081f",
    "--lms-paper-2": "#1d1033",
    "--lms-surface": "#180d28",
    "--lms-navy": "#0c0616",
    "--lms-navy-2": "#07030e",
    "--lms-navy-3": "#2e1a4a",
    "--lms-primary": "#c4b5fd",
    "--lms-primary-fg": "#12081f",
    "--lms-accent": "#ddd6fe",
    "--lms-line": "#2a1848",
    "--lms-line-strong": "#43246e",
    "--lms-ok": "#6ee7b7",
    "--lms-ok-bg": "#064e3b",
    "--lms-warn": "#fbbf24",
    "--lms-warn-bg": "#422006",
    "--lms-danger": "#fb7185",
    "--lms-danger-bg": "#4c0519",
    "--lms-info-bg": "#1d1033",
    "--lms-heading": "#ede9fe",
  },
};

export function isThemeId(v: string | null | undefined): v is ThemeId {
  return THEMES.some((t) => t.id === v);
}

export function isBackgroundId(v: string | null | undefined): v is BackgroundId {
  return BACKGROUNDS.some((b) => b.id === v);
}

export function isDarkTheme(id: ThemeId) {
  return THEMES.find((t) => t.id === id)?.scheme === "dark";
}

export function readStoredTheme(): ThemeId {
  if (typeof window === "undefined") return "campus";
  const v = window.localStorage.getItem(THEME_KEY);
  return isThemeId(v) ? v : "campus";
}

export function readStoredBackground(): BackgroundId {
  if (typeof window === "undefined") return "linen";
  const v = window.localStorage.getItem(BACKGROUND_KEY);
  return isBackgroundId(v) ? v : "linen";
}

export function applyAppearance(theme: ThemeId, background: BackgroundId) {
  if (typeof document === "undefined") return;
  const root = document.documentElement;
  const dark = isDarkTheme(theme);
  root.dataset.theme = theme;
  root.dataset.bg = background;
  root.dataset.scheme = dark ? "dark" : "light";
  root.style.colorScheme = dark ? "dark" : "light";
  root.classList.toggle("dark", dark);
  const tokens = THEME_TOKENS[theme];
  for (const [key, value] of Object.entries(tokens)) {
    root.style.setProperty(key, value);
  }
  root.style.color = tokens["--lms-ink"] ?? "";
  root.style.backgroundColor = tokens["--lms-paper"] ?? "";
}
