/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppClassesRouteImport } from './routes/_app/classes'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppMaterialsRouteImport } from './routes/_app/materials'
import { Route as AppMeetingsRouteImport } from './routes/_app/meetings'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppResultsRouteImport } from './routes/_app/results'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStudentsRouteImport } from './routes/_app/students'
import { Route as AppSubjectsRouteImport } from './routes/_app/subjects'
import { Route as AppTeachersRouteImport } from './routes/_app/teachers'
import { Route as AppTimetableRouteImport } from './routes/_app/timetable'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppAssignmentsIndexRouteImport } from './routes/_app/assignments.index'
import { Route as AppAssignmentsIdRouteImport } from './routes/_app/assignments.$id'
import { Route as AppForumIndexRouteImport } from './routes/_app/forum.index'
import { Route as AppForumIdRouteImport } from './routes/_app/forum.$id'
import { Route as AppQuizzesIndexRouteImport } from './routes/_app/quizzes.index'
import { Route as AppQuizzesIdRouteImport } from './routes/_app/quizzes.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialsRoute = AppMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAssignmentsIndexRoute = AppAssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAssignmentsIdRoute = AppAssignmentsIdRouteImport.update({
  id: '/assignments/$id',
  path: '/assignments/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppForumIndexRoute = AppForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppForumIdRoute = AppForumIdRouteImport.update({
  id: '/forum/$id',
  path: '/forum/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuizzesIndexRoute = AppQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuizzesIdRoute = AppQuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/attendance': typeof AppAttendanceRoute
  '/calendar': typeof AppCalendarRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/materials': typeof AppMaterialsRoute
  '/meetings': typeof AppMeetingsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/subjects': typeof AppSubjectsRoute
  '/teachers': typeof AppTeachersRoute
  '/timetable': typeof AppTimetableRoute
  '/users': typeof AppUsersRoute
  '/assignments/$id': typeof AppAssignmentsIdRoute
  '/forum/$id': typeof AppForumIdRoute
  '/quizzes/$id': typeof AppQuizzesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/assignments/': typeof AppAssignmentsIndexRoute
  '/forum/': typeof AppForumIndexRoute
  '/quizzes/': typeof AppQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/attendance': typeof AppAttendanceRoute
  '/calendar': typeof AppCalendarRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/materials': typeof AppMaterialsRoute
  '/meetings': typeof AppMeetingsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/subjects': typeof AppSubjectsRoute
  '/teachers': typeof AppTeachersRoute
  '/timetable': typeof AppTimetableRoute
  '/users': typeof AppUsersRoute
  '/assignments/$id': typeof AppAssignmentsIdRoute
  '/forum/$id': typeof AppForumIdRoute
  '/quizzes/$id': typeof AppQuizzesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/assignments': typeof AppAssignmentsIndexRoute
  '/forum': typeof AppForumIndexRoute
  '/quizzes': typeof AppQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/materials': typeof AppMaterialsRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/subjects': typeof AppSubjectsRoute
  '/_app/teachers': typeof AppTeachersRoute
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/assignments/$id': typeof AppAssignmentsIdRoute
  '/_app/forum/$id': typeof AppForumIdRoute
  '/_app/quizzes/$id': typeof AppQuizzesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/assignments/': typeof AppAssignmentsIndexRoute
  '/_app/forum/': typeof AppForumIndexRoute
  '/_app/quizzes/': typeof AppQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/attendance'
    | '/calendar'
    | '/classes'
    | '/dashboard'
    | '/materials'
    | '/meetings'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/results'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/timetable'
    | '/users'
    | '/assignments/$id'
    | '/forum/$id'
    | '/quizzes/$id'
    | '/api/auth/$'
    | '/assignments/'
    | '/forum/'
    | '/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/attendance'
    | '/calendar'
    | '/classes'
    | '/dashboard'
    | '/materials'
    | '/meetings'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/results'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/timetable'
    | '/users'
    | '/assignments/$id'
    | '/forum/$id'
    | '/quizzes/$id'
    | '/api/auth/$'
    | '/assignments'
    | '/forum'
    | '/quizzes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/attendance'
    | '/_app/calendar'
    | '/_app/classes'
    | '/_app/dashboard'
    | '/_app/materials'
    | '/_app/meetings'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/results'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/students'
    | '/_app/subjects'
    | '/_app/teachers'
    | '/_app/timetable'
    | '/_app/users'
    | '/_app/assignments/$id'
    | '/_app/forum/$id'
    | '/_app/quizzes/$id'
    | '/api/auth/$'
    | '/_app/assignments/'
    | '/_app/forum/'
    | '/_app/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/materials': {
      id: '/_app/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AppMaterialsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/subjects': {
      id: '/_app/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/assignments/': {
      id: '/_app/assignments/'
      path: '/assignments'
      fullPath: '/assignments/'
      preLoaderRoute: typeof AppAssignmentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/assignments/$id': {
      id: '/_app/assignments/$id'
      path: '/assignments/$id'
      fullPath: '/assignments/$id'
      preLoaderRoute: typeof AppAssignmentsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/forum/': {
      id: '/_app/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof AppForumIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/forum/$id': {
      id: '/_app/forum/$id'
      path: '/forum/$id'
      fullPath: '/forum/$id'
      preLoaderRoute: typeof AppForumIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/': {
      id: '/_app/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof AppQuizzesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quizzes/$id': {
      id: '/_app/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof AppQuizzesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClassesRoute: typeof AppClassesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMaterialsRoute: typeof AppMaterialsRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppUsersRoute: typeof AppUsersRoute
  AppAssignmentsIdRoute: typeof AppAssignmentsIdRoute
  AppForumIdRoute: typeof AppForumIdRoute
  AppQuizzesIdRoute: typeof AppQuizzesIdRoute
  AppAssignmentsIndexRoute: typeof AppAssignmentsIndexRoute
  AppForumIndexRoute: typeof AppForumIndexRoute
  AppQuizzesIndexRoute: typeof AppQuizzesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClassesRoute: AppClassesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMaterialsRoute: AppMaterialsRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppResultsRoute: AppResultsRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppUsersRoute: AppUsersRoute,
  AppAssignmentsIdRoute: AppAssignmentsIdRoute,
  AppForumIdRoute: AppForumIdRoute,
  AppQuizzesIdRoute: AppQuizzesIdRoute,
  AppAssignmentsIndexRoute: AppAssignmentsIndexRoute,
  AppForumIndexRoute: AppForumIndexRoute,
  AppQuizzesIndexRoute: AppQuizzesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
